<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
            font-size: 14px;
        }
        .header, .footer {
            text-align: right;
            margin-bottom: 20px;
        }
        .section {
            margin-bottom: 20px;
        }
        .section h2 {
            border-bottom: 1px solid #000;
            padding-bottom: 5px;
            margin-bottom: 10px;
        }
        .table {
            width: 100%;
            border-collapse: collapse;
        }
        .table th, .table td {
            border: 1px solid #000;
            padding: 8px;
            text-align: left;
        }
        .table th {
            background-color: #f2f2f2;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Job Order Report</h1>
    </div>

    <table class="table">
        <thead>
            <tr>
                <th>Title</th>
                <th>Unit Name</th>
                <th>Date Requested</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($jobOrders as $jobOrder)
                <tr>
                    <td>{{ $jobOrder->job_order_title }}</td>
                    <td>{{ $jobOrder->unit_name }}</td>
                    <td>{{ \Carbon\Carbon::parse($jobOrder->date_requested)->format('M j, Y') }}</td>
                    <td>{{ $jobOrder->status }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>Generated by DomPDF</p>
    </div>
</body>
</html>
